#!/usr/bin/env python3
"""Generate section-addressed read aids so agents load a slice, not a whole file.

  references/TOC.md               index: file -> its TOC, size in tokens (bytes/4)
  references/toc/<name>.md        per-file heading -> line range (+ ~tokens) for big files
  schema/perspective/digest/<component>.md
                                  props-only digest for fat component schemas
Regenerate after editing any reference or schema:  python3 scripts/gen_toc.py
Read a section with:  Read <file> offset=<start> limit=<end-start+1>
"""
import glob, json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
REF = os.path.join(ROOT, "references")
TOC_MIN = 24000          # bytes (~6k tokens): smaller files are cheaper to read whole
ALWAYS_TOC = {"ignition-8-3/8.1-to-8.3-traps.md"}   # small, but read by section
DIGEST_MIN = 16000       # bytes: by-id schemas above this get a digest


def tok(n):
    return "%.1fk" % (n / 4000.0)


def gen_toc():
    files = []
    for p in sorted(glob.glob(REF + "/**/*.md", recursive=True)):
        rel = os.path.relpath(p, REF)
        if rel.startswith("toc/") or rel in ("TOC.md", "INDEX.md"):
            continue
        if os.path.getsize(p) >= TOC_MIN or rel in ALWAYS_TOC:
            files.append((rel, p))
    outdir = os.path.join(REF, "toc")
    os.makedirs(outdir, exist_ok=True)
    for old in glob.glob(outdir + "/*.md"):
        os.remove(old)
    index = ["# Section index for big reference files",
             "",
             "Files under ~6k tokens are read whole. For the files below, open the matching",
             "`toc/<name>.md` (1-3k tokens), pick sections, then `Read <file> offset=<start> limit=<n>`.",
             "Generated by `scripts/gen_toc.py` — do not edit.", "",
             "| File | ~Tokens | Sections | TOC |", "|---|---|---|---|"]
    for rel, p in files:
        lines = open(p, encoding="utf-8").read().split("\n")
        heads = []
        fence = False
        for i, l in enumerate(lines, 1):
            if l.startswith("```"):
                fence = not fence
            m = re.match(r"(#{2,3}) (.+)", l)
            if m and not fence:
                heads.append((i, len(m.group(1)), m.group(2).strip()))
        name = rel.replace("/", "__")
        out = ["# TOC: references/%s" % rel, "",
               "%d lines, ~%s tokens. Line ranges are 1-based inclusive; `Read` with offset=start, limit=end-start+1." % (len(lines), tok(os.path.getsize(p))), ""]
        cum = [0]
        for l in lines:
            cum.append(cum[-1] + len(l.encode("utf-8")) + 1)
        for k, (ln, lvl, title) in enumerate(heads):
            end = heads[k + 1][0] - 1 if k + 1 < len(heads) else len(lines)
            out.append("%sL%d-%d (%s) %s%s" % ("  " if lvl == 3 else "", ln, end, tok(cum[end] - cum[ln - 1]), "## " if lvl == 2 else "### ", title))
        open(os.path.join(outdir, name), "w", encoding="utf-8").write("\n".join(out) + "\n")
        index.append("| `%s` | %s | %d | `toc/%s` |" % (rel, tok(os.path.getsize(p)), len(heads), name))
    open(os.path.join(REF, "TOC.md"), "w", encoding="utf-8").write("\n".join(index) + "\n")
    return len(files)


def _walk(props, prefix, depth, out, limit=3):
    for k, v in props.items():
        if not isinstance(v, dict):
            continue
        t = v.get("type")
        t = "|".join(t) if isinstance(t, list) else (t or "")
        bits = [t]
        if "enum" in v:
            bits.append("enum=" + ",".join(map(str, v["enum"][:12])))
        if "default" in v and not isinstance(v["default"], (dict, list)):
            bits.append("default=%s" % json.dumps(v["default"]))
        desc = (v.get("description") or "").split(". ")[0][:90]
        out.append("%s%s%s: %s%s" % ("  " * depth, prefix, k, " ".join(b for b in bits if b), (" — " + desc) if desc else ""))
        if depth + 1 < limit:
            sub = v.get("properties") or (v.get("items") or {}).get("properties")
            if isinstance(sub, dict):
                _walk(sub, "[]" if "items" in v and "properties" not in v else "", depth + 1, out, limit)


def gen_digests():
    src = os.path.join(ROOT, "schema", "perspective", "by-id")
    dst = os.path.join(ROOT, "schema", "perspective", "digest")
    os.makedirs(dst, exist_ok=True)
    for old in glob.glob(dst + "/*.md"):
        os.remove(old)
    n = 0
    for p in sorted(glob.glob(src + "/*.json")):
        if os.path.getsize(p) < DIGEST_MIN:
            continue
        d = json.load(open(p))
        s = d.get("schema", {})
        out = ["# %s (digest)" % d.get("id", os.path.basename(p)), "",
               "Props-only digest (depth 3) of `../by-id/%s` (~%s tokens full). Read the full JSON only for an exact" % (os.path.basename(p), tok(os.path.getsize(p))),
               "nested default/enum/description not shown here. Generated by `scripts/gen_toc.py`.", "",
               "## props", ""]
        _walk(s.get("properties", {}), "", 0, out)
        ev = [e.get("name") for e in d.get("events", []) if isinstance(e, dict)]
        if ev:
            out += ["", "## events", "", ", ".join(ev)]
        open(os.path.join(dst, os.path.basename(p)[:-5] + ".md"), "w").write("\n".join(out) + "\n")
        n += 1
    return n


if __name__ == "__main__":
    print("toc files:", gen_toc(), "digests:", gen_digests())
